broker:
    host: "localhost"
    port: 1883
    user: ""
    password: ""

# Общие настройки (по умолчанию) для всех объектов приложения
cfg:
  pool_period_ms: 100
  changes_only: True
  status_period_sec: 600


sysfs_pins:

  # - title: none                           # ! Начало описания элемента - обязательно отбивка через дефис и выравнивание
  #   name: TEXT                            # * Символическое имя, используемое для ссылок
  #   type: IN | OUT                        # !  
  #   pool_period_ms: #                     # * Возможность задать независимое время опроса
  #   changes_only: BOOL                    # * Возможность передавать только изменения параметра
  #   status_period_sec: #                  # * При установке параметра осуществляется периодическая безусловная передача значения
  #   topic: "full/path/to/topic_name"      # ! топик для значения - сокращенная запись для чтения и записи
  #   topic_wr: "full/path/wr/topic_name"   # * топик только для управления. Альтернативное название - topic_cmd
  #   topic_rd: "full/path/rd/topic_name"   # * топик только для чтения значений. Альтернативное название - topic_rd
  #   file_value: "full/path/to/file_name"  # ! файл для записи значения
  #   create_start_topic: BOOL              # * Для удобства оператора - топики управления и чтения создается при старте
  #   init:                                 # * Инициализирующая последовательность при старте
  #     - file: "full/path/to/file_name1"   # * файл для записи значения
  #       text: "#"                         # * текст для записи в файл 
  #     - file: "full/path/to/file_name2"   # * Записей может быть несколько
  #       text: "#"
  #   convert_table:                        # * Таблица преобразований из значения брокера в файл контроллера
  #     - broker: "True"                    # * Строка получаемая с брокера
  #       file: "1"                         # * Реальное значение для записи в файл
  #     - broker: TEXT
  #       file: TEXT
