broker:
  host: "localhost"
  port: 1883
  user: ""
  password: ""

cfg:
  pool_period_ms: 100
  changes_only: True
  status_period_sec: 10

convert_tables:
  - &bin_filter 
    - name: on_value
      broker: 1
      file: 1
    - name: off_value
      broker: 0
      file: 0
    - broker: "*"
      file: null
    - broker: null
      file: "*"      
  - &bool_to_bin 
    - broker: "True"
      file: 1
    - broker: "False"
      file: 0
    - broker: "*"
      file: null
    - broker: null
      file: "*"

ext_i2c:
    # Секция описывает расположение боковых модулей ввода/вывода
    # начиная со стороны контроллера

    common_path: devices
    # общий путь для всех топиков секции
    # опционально.
    # если не установлено - то используется пустое значение - обращение начинается от корня: "/"

    repetition_time_sec: 500
    # период принудительного опроса и отправки состояния в брокер
    # опционально.
    # если не установлено или 0 - то отправка только по изменению

    reset_to_def_topic: reset_all
    # пример: Relative/Path/To/Set/Topic 
    # итоговое значение для записи: common_path/reset_to_def_topic
    # топик для сброса всех выходов в исходное состояние
    # опционально.

    # боковые модули

    # модули одинакового вида (DO/DI) располагаются одной группой
    # не более 4 модулей одного вида (DO/DI)
    # не более 8 модулей DO/DI всего
    
    # поддерживаемые варианты:
    #- wbio-do-r1g-16  # Модуль релейных выходов 1А для контакторов
    #- wbio-do-r3a-8   # Модуль релейных выходов 3A
    #- wbio-do-ssr-8   # Модуль дискретных выходов типа «сухой контакт»
    #- wbio-di-hvd-16  # Модуль-детектор наличия сетевого напряжения 230 В
    #- wbio-di-hvd-8   # Модуль-детектор наличия сетевого напряжения 230 В
    #- wbio-di-dr-14   # Модуль дискретных входов типа "сухой контакт"
    #- wbio-di-dr-8    # Модуль дискретных входов типа "сухой контакт"
    
    #- do#            # модуль дискретных вЫходов разрядностью "#"
    #- di#            # модуль дискретных входов разрядностью "#"

    modules:
      # отбика каждой следующей дочерней секции производится через отступы и символы "-"

      - type: do16  
        # тип модуля из поддерживаемых вариантов

        repetition_time_sec: 500
        # период принудительного опроса и отправки состояния в брокер
        # индивидуально для данного конкретного модуля
        # опционально.
        # если не установлено - то используется значение из вышестоящей секции

        control_path: do16/controls
        # относительный путь для управления и индикации состояния данного конкретного модуля
        # сценарий: используется для добавления дополнительных уровней в имя топика
        # пример: module_name/control
        # итоговое значение для записи и чтения:"common_path"/"control_path"
        # опционально.
        # если не установлено - то используется порядковый номер модуля на дин рейке

        start_state: "None"
        # start_state: [0, 1, "LastState", "None"]
        # установить состояние модуля вывода при старте сервиса
        # 0 - сбросить все контакты
        # 1 - взвести все контакты
        # "LastState" - восстановить последнее установленное значение
        # "None" - ничего не предпринимать
        # опционально.
        # если не установлено - то используется "None"

        pins:
        # настройки для контактов модулей индивидуально
        # опционально.
        # если не установлено - то для отображения используется порядковый номер контактов модуля

        - num: 1 
          # номер контакта, к которому задаются индивидуальные настройки
          # допускаются пропуски и нумерация не по порядку
          # нумерация начинается с 1

          name: "PinOne"
          # мнемоническое имя для управления топиком
          # опционально.
          # если не установлено - то используется номер контакта
          
          set_path: set
          # имя топика для установки значения
          # итоговое значение для записи:"common_path"/"control_path"/"name"/"set_path"
          # опционально.
          # если не установлено - то используется значение "set"         

          clr_path: clr
          # имя топика для сброса значения
          # итоговое значение для записи:"common_path"/"control_path"/"name"/"clr_path"
          # опционально.
          # если не установлено - то используется значение "clr"   

          repetition_time_sec: 500
          # период принудительного отправки состояния в брокер
          # дополнительно для данного конкретного контакта
          # опционально.
          # если не установлено - то все состояния контактов отправляются одновременно для каждого модуля
          # Warning: дополнительный опрос модуля не производится!

          start_state: "None"
          # start_state: [0, 1, "LastState", "None"]
          # установить состояние контакта вывода при старте сервиса
          # 0 - сбросить контакт
          # 1 - установить контакт
          # "LastState" - восстановить последнее установленное значение
          # "None" - ничего не предпринимать
          # опционально.
          # если не установлено - то используется значение из вышестоящей секции
          # значения 0, 1, "LastState" - перезаписываЮТ соответствующие поля вышестоящей секции
          # значение "None" - перезаписываЮТСЯ соответствующиМИ поляМИ вышестоящей секции

      - type: di8


sysfs_pins:

  # - title: none                           # ! Начало описания элемента
  #   name: TEXT                            # * Символическое имя, используемое для ссылок
  #   type: IN | OUT                        # !  
  #   pool_period_ms: #                     # * Возможность задать независимое время опроса
  #   changes_only: BOOL                    # * Возможность передавать только изменения параметра
  #   topic: "full/path/to/topic_name"      # ! топик для управления значением
  #   file_value: "full/path/to/file_name"  # ! файл для записи значения
  #   create_start_topic: BOOL              # * Для удобства топик управления создается при старте
  #   init:                                 # * Инициализирующая последовательность при старте
  #     - file: "full/path/to/file_name1"   # * файл для записи значения
  #       text: "#"                         # * текст для записи в файл 
  #     - file: "full/path/to/file_name2"   # * Записей может быть несколько
  #       text: "#""

  # the following data could be used for test purposes
  # JH D1
  # - name: LedRed
  #   type: OUT
  #   pool_period_ms: 100
  #   changes_only: False
  #   topic: "test/dev/LedRed"
  #   file_value: "/sys/class/gpio/gpio538/value"
  #   create_start_topic: True
  #   init:
  #     - file: "/sys/class/gpio/export"
  #       text: "538"
  #     - file: "/sys/class/gpio/gpio563/direction"
  #       text: "out"

  # - name: LedGreen
  #   type: OUT
  #   topic: "test/dev/LedGreen"
  #   file_value: "/sys/class/gpio/gpio539/value"
  #   create_start_topic: True

  # - name: UserBtn
  #   type: IN
  #   pool_period_ms: 100
  #   changes_only: True
  #   topic: "test/dev/UserBtn"
  #   file_value: "/sys/class/gpio/gpio522/value"
  #   create_start_topic: True
  #   init:
  #     - text: "563"
  #       file: "/sys/class/gpio/export"
  #     - file: "/sys/class/gpio/gpio522/direction"
  #       text: "in"  


  # - name: DI_1
  #   type: IN
  #   topic: "test/dev/DI_1"
  #   file_value: "/sys/class/gpio/gpio558/value"
  #   create_start_topic: True
  #   changes_only: True

  # - name: DI_2
  #   type: IN
  #   topic: "test/dev/DI_2"
  #   file_value: "/sys/class/gpio/gpio557/value"
  #   create_start_topic: True    

  # - name: DI_3
  #   type: IN
  #   topic: "test/dev/DI_3"
  #   file_value: "/sys/class/gpio/gpio556/value"
  #   create_start_topic: True

  # - name: DI_4
  #   type: IN
  #   topic: "test/dev/DI_4"
  #   file_value: "/sys/class/gpio/gpio555/value"
  #   create_start_topic: True

##############################################################33
# Section
#############################################################33

#   - name: DO_1
#     type: OUT
#     #topic_wr: "test/dev/DO_1/on"
#     topic_rd: "test/dev/DO_1"
#     topic_cmd: "test/dev/DO_1/on"
#     #topic_state: "test/dev/DO_1"
#     convert_table: 
#       - broker: "True"
#         file: "1"
#       - broker: "False"
#         file: "0"
#       - broker: "*"
#         file: null
#       - broker: null
#         file: "*"
#     file_value: "/sys/class/gpio/gpio542/value"
#     create_start_topic: True
#     changes_only: True
#     pool_period_ms: 1000
#     status_period_sec: 600

# ######################################################################

#   - name: DO_2
#     type: OUT
#     topic_wr: "test/dev/DO_2/on"
#     topic_rd: "test/dev/DO_2"
#     file_value: "/sys/class/gpio/gpio541/value"
#     create_start_topic: True    
#     changes_only: True

#   - name: DO_3
#     type: OUT
#     topic_wr: "test/dev/DO_3/on"
#     topic_rd: "test/dev/DO_3"
#     file_value: "/sys/class/gpio/gpio540/value"
#     create_start_topic: True
#     changes_only: True


  # WB7
  # - name: Mod1_K12
  #   pool_period_ms: 100
  #   changes_only: False
  #   topic: "dev/extender/do12"
  #   file_value: "/sys/class/gpio/gpio563/value"
  #   type: OUT
  #   create_start_topic: True
  #   init:
  #     - file: "/sys/class/gpio/export"
  #       text: "563"
  #     - file: "/sys/class/gpio/gpio563/direction"
  #       text: "out"
  # - name: Mod2_DI1
  #   pool_period_ms: 100
  #   changes_only: False
  #   topic: "dev/extender/di1"
  #   file_value: "/sys/class/gpio/gpio512/value"
  #   type: IN
  #   create_start_topic: True
  #   init:
  #     - file: "/sys/class/gpio/export"
  #       text: "563"
  #     - file: "/sys/class/gpio/gpio563/direction"
  #       text: "in"  

