broker:
    host: "localhost"
    port: 1883
    user: ""
    password: ""

# Общие настройки (по умолчанию) для всех объектов приложения
cfg:
  pool_period_ms: 100           # период опроса контактов
  changes_only: True            # передавать на брокер только изменение состояния
  status_period_sec: 600        # период принудительной передачи текущего состояния