
convert_tables:
  - &bin_filter                             # ! символическое имя для дальнейшего использования
    - name: on_value                        # * наименование состояния
      broker: 1                             # ! Команда с брокера
      file: 1                               # ! значение для записи в файл
    - name: off_value
      broker: 0
      file: 0
    - broker: "*"
      file: null
    - broker: null
      file: "*"    

sysfs_pins:
  # - title: none                           # ! Начало описания элемента
  #   name: TEXT                            # * Символическое имя, используемое для ссылок
  #   type: IN | OUT                        # !  
  #   pull_period_ms: #                     # * Возможность задать независимое время опроса
  #   changes_only: BOOL                    # * Возможность передавать только изменения параметра
  #   topic: "full/path/to/topic_name"      # ! топик для управления значением
  #   topic_rd: "test/dev/DO_1"             # * топик для чтения значения - синоним для раздельного управления
  #   topic_cmd: "test/dev/DO_1/on"         # * топик для управления значением - синоним  для раздельного управления
  #   file_value: "full/path/to/file_name"  # ! файл для записи значения
  #   create_start_topic: BOOL              # * Для удобства топик управления создается при старте
  #   invert: False                         # * Инвертировать значение электрического сигнала на выходе
  #   init:                                 # * Инициализирующая последовательность при старте
  #     - file: "full/path/to/file_name1"   # * файл для записи значения
  #       text: "#"                         # * текст для записи в файл 
  #     - file: "full/path/to/file_name2"   # * Записей может быть несколько
  #       text: "#""